/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminUserSummaryDto { 
    username: string;
    role: AdminUserSummaryDtoRoleEnum;
    mustChangePassword: boolean;
    createdAt: string;
}
export enum AdminUserSummaryDtoRoleEnum {
    Admin = 'admin',
    Readonly = 'readonly'
};



