/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditEvent { 
    id: string;
    ts: string;
    event: string;
    subject: string | null;
    requestId: string | null;
    bucket: string | null;
    objectKey: string | null;
    keyId: string | null;
    ip: string | null;
    detail: { [key: string]: any; } | null;
}

