/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditEvent } from './audit-event';


export interface AuditPageDto { 
    items: Array<AuditEvent>;
    nextCursor: string | null;
}

