/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BucketReplicationStatusDto { 
    bucket: string;
    pendingCount: number;
    inflightCount: number;
    failedCount: number;
    oldestPendingAgeMs: number | null;
}

