/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BucketSummaryDto { 
    name: string;
    createdAt: string;
    versioning: BucketSummaryDtoVersioningEnum;
    objectLock: boolean;
    objectCount: number;
    sizeBytes: number;
}
export enum BucketSummaryDtoVersioningEnum {
    Disabled = 'disabled',
    Enabled = 'enabled',
    Suspended = 'suspended'
};



