/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BucketBreakdownItemDto } from './bucket-breakdown-item-dto';


export interface BucketBreakdownDto { 
    buckets: Array<BucketBreakdownItemDto>;
    totalSizeBytes: number;
    totalObjectCount: number;
}

