/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkDeleteErrorItem } from './bulk-delete-error-item';
import { BulkDeleteDeletedItem } from './bulk-delete-deleted-item';


export interface BulkDeleteResponseDto { 
    deleted: Array<BulkDeleteDeletedItem>;
    errors: Array<BulkDeleteErrorItem>;
}

