/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkDeleteDtoKeysInner } from './bulk-delete-dto-keys-inner';


export interface BulkDeleteDto { 
    keys: Array<BulkDeleteDtoKeysInner>;
}

