/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorruptObjectDto } from './corrupt-object-dto';


export interface CorruptListDto { 
    rows: Array<CorruptObjectDto>;
    total: number;
}

