/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorsRuleDto } from './cors-rule-dto';


export interface CorsConfigDto { 
    rules: Array<CorsRuleDto>;
}

