/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CorsRuleDto { 
    id?: string;
    allowedOrigins: Array<string>;
    allowedMethods: Array<CorsRuleDtoAllowedMethodsEnum>;
    allowedHeaders?: Array<string>;
    exposeHeaders?: Array<string>;
    maxAgeSeconds?: number;
}
export enum CorsRuleDtoAllowedMethodsEnum {
    Get = 'GET',
    Put = 'PUT',
    Post = 'POST',
    Delete = 'DELETE',
    Head = 'HEAD'
};



