/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipal } from './create-key-dto-scope-one-of1-document-statement-inner-principal';
import { CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOfAWS } from './create-key-dto-scope-one-of1-document-statement-inner-principal-any-of-aws';


export interface CreateKeyDtoScopeOneOf1DocumentStatementInner { 
    Sid?: string;
    Effect: CreateKeyDtoScopeOneOf1DocumentStatementInnerEffectEnum;
    Principal: CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipal;
    Action: CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOfAWS;
    Resource: CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOfAWS;
    Condition?: { [key: string]: { [key: string]: CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOfAWS; }; };
}
export enum CreateKeyDtoScopeOneOf1DocumentStatementInnerEffectEnum {
    Allow = 'Allow',
    Deny = 'Deny'
};



