/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateKeyDtoScope } from './create-key-dto-scope';


export interface CreateKeyDto { 
    label: string;
    scope?: CreateKeyDtoScope;
}

