/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBucketDto { 
    name: string;
    versioning?: CreateBucketDtoVersioningEnum;
    objectLock?: boolean;
    region?: string;
}
export enum CreateBucketDtoVersioningEnum {
    Disabled = 'disabled',
    Enabled = 'enabled'
};



