/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateKeyDtoScopeOneOf { 
    kind: CreateKeyDtoScopeOneOfKindEnum;
    bucket: string;
    prefix?: string;
    actions?: Array<string>;
}
export enum CreateKeyDtoScopeOneOfKindEnum {
    Prefix = 'prefix'
};



