/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOf } from './create-key-dto-scope-one-of1-document-statement-inner-principal-any-of';
import { CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOfAWS } from './create-key-dto-scope-one-of1-document-statement-inner-principal-any-of-aws';


export interface CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipal { 
    AWS: CreateKeyDtoScopeOneOf1DocumentStatementInnerPrincipalAnyOfAWS;
}

