/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAdminUserDto { 
    username: string;
    password: string;
    role: CreateAdminUserDtoRoleEnum;
}
export enum CreateAdminUserDtoRoleEnum {
    Admin = 'admin',
    Readonly = 'readonly'
};



