/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateKeyDtoScopeOneOf1Document } from './create-key-dto-scope-one-of1-document';


export interface CreateKeyDtoScopeOneOf1 { 
    kind: CreateKeyDtoScopeOneOf1KindEnum;
    document: CreateKeyDtoScopeOneOf1Document;
}
export enum CreateKeyDtoScopeOneOf1KindEnum {
    Policy = 'policy'
};



