/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateKeyDtoScopeOneOf } from './create-key-dto-scope-one-of';
import { CreateKeyDtoScopeOneOf1Document } from './create-key-dto-scope-one-of1-document';
import { CreateKeyDtoScopeOneOf1 } from './create-key-dto-scope-one-of1';


/**
 * @type CreateKeyDtoScope
 * @export
 */
export type CreateKeyDtoScope = CreateKeyDtoScopeOneOf | CreateKeyDtoScopeOneOf1;

