/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateKeyDtoScopeOneOf1DocumentStatementInner } from './create-key-dto-scope-one-of1-document-statement-inner';


export interface EffectivePermissionsDtoScope { 
    Version: EffectivePermissionsDtoScopeVersionEnum;
    Statement: Array<CreateKeyDtoScopeOneOf1DocumentStatementInner>;
}
export enum EffectivePermissionsDtoScopeVersionEnum {
    _20121017 = '2012-10-17'
};



