/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EffectivePermissionsDtoMatrixInner { 
    action: string;
    resource: string;
    decision: EffectivePermissionsDtoMatrixInnerDecisionEnum;
}
export enum EffectivePermissionsDtoMatrixInnerDecisionEnum {
    Allow = 'allow',
    Deny = 'deny'
};



