/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EffectivePermissionsDtoScope } from './effective-permissions-dto-scope';
import { EffectivePermissionsDtoMatrixInner } from './effective-permissions-dto-matrix-inner';


export interface EffectivePermissionsDto { 
    scoped: boolean;
    scope: EffectivePermissionsDtoScope | null;
    matrix: Array<EffectivePermissionsDtoMatrixInner>;
}

