/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IntegrityStatusDto { 
    enabled: boolean;
    scanned: number;
    ok: number;
    corrupt: number;
    unchecked: number;
    repaired: number;
    lastRunAt: string | null;
    cursor: string | null;
}

