/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KeySummaryDtoScope { 
    kind: KeySummaryDtoScopeKindEnum;
    bucket?: string;
    prefix?: string;
}
export enum KeySummaryDtoScopeKindEnum {
    Prefix = 'prefix',
    Policy = 'policy'
};



