/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LifecycleRuleDtoFilter } from './lifecycle-rule-dto-filter';


export interface LifecycleRuleDto { 
    id: string;
    status: LifecycleRuleDtoStatusEnum;
    prefix?: string;
    filter?: LifecycleRuleDtoFilter;
    expirationDays?: number;
    expiredObjectDeleteMarker?: boolean;
    noncurrentVersionExpirationDays?: number;
    abortIncompleteMultipartUploadDays?: number;
}
export enum LifecycleRuleDtoStatusEnum {
    Enabled = 'Enabled',
    Disabled = 'Disabled'
};



