/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LifecycleRuleDto } from './lifecycle-rule-dto';


export interface LifecycleConfigDto { 
    rules: Array<LifecycleRuleDto>;
}

