/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LifecycleRuleDtoFilterTag } from './lifecycle-rule-dto-filter-tag';


export interface LifecycleRuleDtoFilter { 
    tag?: LifecycleRuleDtoFilterTag;
    sizeGreaterThan?: number;
    sizeLessThan?: number;
}

