/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectListItem } from './object-list-item';


export interface ListObjectsResponseDto { 
    bucket: string;
    prefix: string;
    delimiter?: string;
    marker?: string;
    nextMarker?: string;
    isTruncated: boolean;
    contents: Array<ObjectListItem>;
    commonPrefixes: Array<string>;
}

