/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BucketSummaryDto } from './bucket-summary-dto';


export interface ListBucketsResponseDto { 
    buckets: Array<BucketSummaryDto>;
    total: number;
}

