/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectSearchHit } from './object-search-hit';


export interface ObjectSearchResponseDto { 
    results: Array<ObjectSearchHit>;
    isTruncated: boolean;
    nextCursor?: string;
}

