/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectVersionDto { 
    key: string;
    versionId: string;
    isLatest: boolean;
    lastModified: string;
    etag: string;
    size: number;
}

