/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectVersionDto } from './object-version-dto';
import { DeleteMarkerDto } from './delete-marker-dto';


export interface ObjectVersionsResponseDto { 
    versions: Array<ObjectVersionDto>;
    deleteMarkers: Array<DeleteMarkerDto>;
    isTruncated: boolean;
    nextKeyMarker?: string;
    nextVersionIdMarker?: string;
}

