/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectMetaDto { 
    key: string;
    bucket: string;
    size: number;
    etag: string;
    contentType: string;
    lastModified: string;
    userMetadata?: { [key: string]: string; };
    tagging?: { [key: string]: string; };
    versionId?: string;
    storageClass: string;
}

