/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectSearchHit { 
    bucket: string;
    key: string;
    size: number;
    etag: string;
    lastModified: string;
    storageClass: string;
    contentType?: string;
}

