/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectLockConfigDto { 
    enabled: boolean;
    mode?: ObjectLockConfigDtoModeEnum;
    defaultRetentionDays?: number;
}
export enum ObjectLockConfigDtoModeEnum {
    Off = 'off',
    Governance = 'governance',
    Compliance = 'compliance'
};



