/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReconcileJobDto { 
    jobId: string;
    scope: ReconcileJobDtoScopeEnum;
    bucket?: string;
    state: ReconcileJobDtoStateEnum;
    localScanned: number;
    remoteScanned: number;
    missingRequeued: number;
    startedAt: string | null;
    finishedAt?: string;
    error?: string;
}
export enum ReconcileJobDtoScopeEnum {
    Instance = 'instance',
    Bucket = 'bucket'
};
export enum ReconcileJobDtoStateEnum {
    Queued = 'queued',
    Running = 'running',
    Completed = 'completed',
    Failed = 'failed'
};



