/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReplicationLastErrorDto } from './replication-last-error-dto';
import { BucketReplicationStatusDto } from './bucket-replication-status-dto';


export interface ReplicationStatusDto { 
    enabled: boolean;
    pendingCount: number;
    inflightCount: number;
    failedCount: number;
    oldestPendingAgeMs: number | null;
    lastError: ReplicationLastErrorDto | null;
    perBucket: Array<BucketReplicationStatusDto>;
}

