/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestPointDto } from './request-point-dto';


export interface RequestSeriesDto { 
    points: Array<RequestPointDto>;
}

