/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeySummaryDtoScope } from './key-summary-dto-scope';


export interface RotatedKeyDto { 
    id: string;
    accessKeyId: string;
    secretAccessKey: string;
    label: string;
    role: string;
    createdAt: string;
    scope: KeySummaryDtoScope | null;
}

