/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleSpecDto } from './schedule-spec-dto';


export interface ScheduleStatusDto { 
    enabled: boolean;
    scope: ScheduleStatusDtoScopeEnum;
    schedule: ScheduleSpecDto;
    lastRunAt: string | null;
    nextRunAt: string | null;
    lastStatus: ScheduleStatusDtoLastStatusEnum;
    lastError: string | null;
    lastDurationMs: number;
    lastBytes: number;
    lastObjectCount: number;
    keepLast: number;
    maxAgeDays: number;
    snapshotCount: number;
}
export enum ScheduleStatusDtoScopeEnum {
    Instance = 'instance',
    Buckets = 'buckets'
};
export enum ScheduleStatusDtoLastStatusEnum {
    Ok = 'ok',
    Error = 'error',
    Skipped = 'skipped'
};



