/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoragePointDto } from './storage-point-dto';


export interface StorageSeriesDto { 
    points: Array<StoragePointDto>;
    bucket: string | null;
}

