/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAdminUserDto { 
    role?: UpdateAdminUserDtoRoleEnum;
    newPassword?: string;
}
export enum UpdateAdminUserDtoRoleEnum {
    Admin = 'admin',
    Readonly = 'readonly'
};



