/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VersioningConfigDto { 
    status: VersioningConfigDtoStatusEnum;
}
export enum VersioningConfigDtoStatusEnum {
    Enabled = 'Enabled',
    Suspended = 'Suspended'
};



