#!/usr/bin/env bash
# Regenerate docs/pm/STATUS.md from the current artifact tree.
#
# Reads YAML front-matter `status:` from every Epic / Story / Task /
# Test Plan, counts by status, surfaces the next ready Story (per
# BACKLOG order), and breaks down progress by milestone (parsed from
# ROADMAP.md).
#
# Usage:
#   ./scripts/pm-status.sh        # writes docs/pm/STATUS.md
#   ./scripts/pm-status.sh --stdout   # prints to stdout instead
#
# Requires: bash, awk, grep, sed, date, git (optional for SHA).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PM="$PROJECT_ROOT/docs/pm"

if [ ! -d "$PM" ]; then
  echo "error: $PM not found" >&2
  exit 1
fi

MODE="${1:-file}"
if [ "$MODE" = "--stdout" ]; then
  OUT=/dev/stdout
else
  OUT="$PM/STATUS.md"
fi

# ---------- collect ----------

# Count statuses across a glob.
count_status() {
  local glob="$1" status="$2"
  grep -lE "^status:[[:space:]]+${status}\$" $glob 2>/dev/null | wc -l | tr -d ' '
}

count_all() {
  local glob="$1"
  ls $glob 2>/dev/null | wc -l | tr -d ' '
}

# Pull (id, title) from a file.
read_id() {
  grep -m1 '^id:' "$1" | sed 's/^id:[[:space:]]*//'
}
read_title() {
  grep -m1 '^title:' "$1" | sed 's/^title:[[:space:]]*//'
}
read_status() {
  grep -m1 '^status:' "$1" | sed 's/^status:[[:space:]]*//'
}
read_epic() {
  grep -m1 '^epic:' "$1" | sed 's/^epic:[[:space:]]*//'
}
read_size() {
  grep -m1 '^size:' "$1" | sed 's/^size:[[:space:]]*//'
}

# Story IDs in BACKLOG.md order.
backlog_order() {
  grep -oE '^[0-9]+\. STORY-[0-9]+' "$PM/BACKLOG.md" | awk '{print $2}'
}

# Map Story ID -> file path.
story_file() {
  local id="$1"
  ls "$PM/stories/${id}-"*.md 2>/dev/null | head -1
}

# Milestone -> list of Story IDs (parses ROADMAP.md).
# Only counts markdown list items (`- STORY-NNNN ...`), so prose mentions in a
# milestone's notes (e.g. the M0 reclassification note referencing STORY-0319 /
# STORY-0313, which actually live under M3) are not miscounted. Dedups per
# milestone so a story listed/mentioned twice in one section counts once.
roadmap_milestones() {
  awk '
    /^## M[0-9]/ {
      milestone=$2
      next
    }
    milestone && /^[[:space:]]*-[[:space:]]+\**STORY-[0-9]+/ {
      match($0, /STORY-[0-9]+/)
      sid=substr($0, RSTART, RLENGTH)
      key=milestone SUBSEP sid
      if (!(key in seen)) {
        seen[key]=1
        print milestone, sid
      }
    }
  ' "$PM/ROADMAP.md"
}

# ---------- header ----------

GEN_TIME="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
GIT_SHA="$(cd "$PROJECT_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo 'no-git')"

# ---------- write ----------

{
  echo "# OpenBucket — PM status"
  echo
  echo "> Generated by \`scripts/pm-status.sh\` at **$GEN_TIME** (git \`$GIT_SHA\`)."
  echo "> Do not hand-edit — re-run the script."
  echo
  echo "---"
  echo

  # --- overall counts ---
  echo "## Counts by status"
  echo
  printf '| Artifact   |'
  for s in backlog ready in_progress review done blocked; do printf ' %s |' "$s"; done
  printf ' total |\n'
  printf '%s' '|------------|'
  for s in backlog ready in_progress review done blocked total; do printf '%s' '---------|'; done
  printf '\n'

  for kind in epics stories tasks test-plans; do
    glob="$PM/$kind/*.md"
    label="$kind"
    printf '| %-10s |' "$label"
    for s in backlog ready in_progress review done blocked; do
      printf ' %s |' "$(count_status "$glob" "$s")"
    done
    printf ' %s |\n' "$(count_all "$glob")"
  done
  echo

  # --- next up ---
  echo "## Next up"
  echo
  echo "First Story in BACKLOG order whose status is \`ready\`:"
  echo
  NEXT_FOUND=0
  for id in $(backlog_order); do
    f="$(story_file "$id")"
    [ -z "$f" ] && continue
    if [ "$(read_status "$f")" = "ready" ]; then
      title="$(read_title "$f")"
      epic="$(read_epic "$f")"
      size="$(read_size "$f")"
      echo "- **$id** — $title — $epic — size $size"
      echo "  - File: \`docs/pm/stories/$(basename "$f")\`"
      NEXT_FOUND=1
      break
    fi
  done
  if [ "$NEXT_FOUND" = 0 ]; then
    echo "_No Story is currently \`ready\`._ Refine the next \`backlog\` Story per"
    echo "\`docs/pm/conventions/workflow.md\` (refinement checklist) and flip its"
    echo "status to \`ready\`."
  fi
  echo

  # --- in progress ---
  echo "## In progress"
  echo
  IP_COUNT=0
  for f in "$PM"/stories/STORY-*.md; do
    [ -f "$f" ] || continue
    if [ "$(read_status "$f")" = "in_progress" ]; then
      id="$(read_id "$f")"
      title="$(read_title "$f")"
      echo "- **$id** — $title"
      IP_COUNT=$((IP_COUNT+1))
    fi
  done
  if [ "$IP_COUNT" = 0 ]; then
    echo "_None._"
  fi
  echo

  # --- blocked ---
  echo "## Blocked"
  echo
  BL_COUNT=0
  for kind in stories tasks; do
    for f in "$PM"/$kind/*.md; do
      [ -f "$f" ] || continue
      if [ "$(read_status "$f")" = "blocked" ]; then
        id="$(read_id "$f")"
        title="$(read_title "$f")"
        echo "- **$id** — $title"
        BL_COUNT=$((BL_COUNT+1))
      fi
    done
  done
  if [ "$BL_COUNT" = 0 ]; then
    echo "_None._"
  fi
  echo

  # --- milestones ---
  echo "## Milestone progress"
  echo
  echo "| Milestone | Stories | done | in_progress | ready | backlog | % done |"
  echo "|-----------|---------|------|-------------|-------|---------|--------|"

  CURRENT_MS=""
  declare -A MS_TOTAL MS_DONE MS_IP MS_RDY MS_BL
  while read -r ms sid; do
    f="$(story_file "$sid")"
    [ -z "$f" ] && continue
    st="$(read_status "$f")"
    MS_TOTAL[$ms]=$(( ${MS_TOTAL[$ms]:-0} + 1 ))
    case "$st" in
      done)        MS_DONE[$ms]=$(( ${MS_DONE[$ms]:-0} + 1 ));;
      in_progress) MS_IP[$ms]=$(( ${MS_IP[$ms]:-0} + 1 ));;
      ready)       MS_RDY[$ms]=$(( ${MS_RDY[$ms]:-0} + 1 ));;
      backlog)     MS_BL[$ms]=$(( ${MS_BL[$ms]:-0} + 1 ));;
    esac
  done < <(roadmap_milestones)

  for ms in M0 M1 M2 M3 M4 M5 M6 M7 M8; do
    total=${MS_TOTAL[$ms]:-0}
    done_n=${MS_DONE[$ms]:-0}
    ip=${MS_IP[$ms]:-0}
    rdy=${MS_RDY[$ms]:-0}
    bl=${MS_BL[$ms]:-0}
    if [ "$total" = 0 ]; then
      pct="—"
    else
      pct=$(( done_n * 100 / total ))%
    fi
    echo "| $ms        | $total       | $done_n    | $ip           | $rdy     | $bl       | $pct  |"
  done
  echo

  # --- footer ---
  echo "---"
  echo
  echo "_Re-run \`./scripts/pm-status.sh\` to refresh._"
} > "$OUT"

if [ "$MODE" != "--stdout" ]; then
  echo "wrote $OUT"
fi
