/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminUserSummaryDto } from '../model/models';
import { CreateAdminUserDto } from '../model/models';
import { UpdateAdminUserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminUsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createAdminUserDto 
     */
    createAdminUser(createAdminUserDto: CreateAdminUserDto, extraHttpRequestParams?: any): Observable<AdminUserSummaryDto>;

    /**
     * 
     * 
     * @param username 
     */
    deleteAdminUser(username: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    listAdminUsers(extraHttpRequestParams?: any): Observable<Array<AdminUserSummaryDto>>;

    /**
     * 
     * 
     * @param username 
     * @param updateAdminUserDto 
     */
    updateAdminUser(username: string, updateAdminUserDto: UpdateAdminUserDto, extraHttpRequestParams?: any): Observable<{}>;

}
