/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BucketBreakdownDto } from '../model/models';
import { RequestSeriesDto } from '../model/models';
import { StorageSeriesDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AnalyticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getBucketBreakdown(extraHttpRequestParams?: any): Observable<BucketBreakdownDto>;

    /**
     * 
     * 
     * @param range 
     * @param bucket 
     */
    getRequestAnalytics(range?: '1h' | '24h' | '7d' | '30d' | '90d', bucket?: string, extraHttpRequestParams?: any): Observable<RequestSeriesDto>;

    /**
     * 
     * 
     * @param range 
     * @param bucket 
     */
    getStorageAnalytics(range?: '1h' | '24h' | '7d' | '30d' | '90d', bucket?: string, extraHttpRequestParams?: any): Observable<StorageSeriesDto>;

}
