export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './buckets-admin.service';
import { BucketsAdminService } from './buckets-admin.service';
export * from './buckets-admin.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './keys-admin.service';
import { KeysAdminService } from './keys-admin.service';
export * from './keys-admin.serviceInterface';
export * from './objects-admin.service';
import { ObjectsAdminService } from './objects-admin.service';
export * from './objects-admin.serviceInterface';
export * from './settings-admin.service';
import { SettingsAdminService } from './settings-admin.service';
export * from './settings-admin.serviceInterface';
export const APIS = [AuthService, BucketsAdminService, HealthService, KeysAdminService, ObjectsAdminService, SettingsAdminService];
