export * from './admin-users.service';
import { AdminUsersService } from './admin-users.service';
export * from './admin-users.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './buckets-admin.service';
import { BucketsAdminService } from './buckets-admin.service';
export * from './buckets-admin.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './keys-admin.service';
import { KeysAdminService } from './keys-admin.service';
export * from './keys-admin.serviceInterface';
export * from './objects-admin.service';
import { ObjectsAdminService } from './objects-admin.service';
export * from './objects-admin.serviceInterface';
export * from './replication-admin.service';
import { ReplicationAdminService } from './replication-admin.service';
export * from './replication-admin.serviceInterface';
export * from './settings-admin.service';
import { SettingsAdminService } from './settings-admin.service';
export * from './settings-admin.serviceInterface';
export const APIS = [AdminUsersService, AuthService, BucketsAdminService, HealthService, KeysAdminService, ObjectsAdminService, ReplicationAdminService, SettingsAdminService];
