/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuditCatalogDto } from '../model/models';
import { AuditPageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuditAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAuditCatalog(extraHttpRequestParams?: any): Observable<AuditCatalogDto>;

    /**
     * 
     * 
     * @param event 
     * @param subject 
     * @param bucket 
     * @param from 
     * @param to 
     * @param cursor 
     * @param limit 
     */
    listAuditEvents(event?: string, subject?: string, bucket?: string, from?: string, to?: string, cursor?: string, limit?: number, extraHttpRequestParams?: any): Observable<AuditPageDto>;

}
