/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RunNowResultDto } from '../model/models';
import { ScheduleStatusDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BackupScheduleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getBackupSchedule(extraHttpRequestParams?: any): Observable<ScheduleStatusDto>;

    /**
     * 
     * 
     */
    runBackupNow(extraHttpRequestParams?: any): Observable<RunNowResultDto>;

}
