/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BucketPolicyDto } from '../model/models';
import { BucketSummaryDto } from '../model/models';
import { CorsConfigDto } from '../model/models';
import { CreateBucketDto } from '../model/models';
import { EncryptionConfigDto } from '../model/models';
import { LifecycleConfigDto } from '../model/models';
import { ListBucketsResponseDto } from '../model/models';
import { ObjectLockConfigDto } from '../model/models';
import { TaggingDto } from '../model/models';
import { VersioningConfigDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BucketsAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createBucketDto 
     */
    createBucket(createBucketDto: CreateBucketDto, extraHttpRequestParams?: any): Observable<BucketSummaryDto>;

    /**
     * 
     * 
     * @param name 
     */
    deleteBucket(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     */
    deleteBucketCors(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     */
    deleteBucketEncryption(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     */
    deleteBucketLifecycle(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     */
    deleteBucketPolicy(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     */
    deleteBucketTagging(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     */
    getBucket(name: string, extraHttpRequestParams?: any): Observable<BucketSummaryDto>;

    /**
     * 
     * 
     * @param name 
     */
    getBucketCors(name: string, extraHttpRequestParams?: any): Observable<CorsConfigDto>;

    /**
     * 
     * 
     * @param name 
     */
    getBucketEncryption(name: string, extraHttpRequestParams?: any): Observable<EncryptionConfigDto>;

    /**
     * 
     * 
     * @param name 
     */
    getBucketLifecycle(name: string, extraHttpRequestParams?: any): Observable<LifecycleConfigDto>;

    /**
     * 
     * 
     * @param name 
     */
    getBucketObjectLock(name: string, extraHttpRequestParams?: any): Observable<ObjectLockConfigDto>;

    /**
     * 
     * 
     * @param name 
     */
    getBucketPolicy(name: string, extraHttpRequestParams?: any): Observable<BucketPolicyDto>;

    /**
     * 
     * 
     * @param name 
     */
    getBucketTagging(name: string, extraHttpRequestParams?: any): Observable<TaggingDto>;

    /**
     * 
     * 
     */
    listBuckets(extraHttpRequestParams?: any): Observable<ListBucketsResponseDto>;

    /**
     * 
     * 
     * @param name 
     * @param corsConfigDto 
     */
    putBucketCors(name: string, corsConfigDto: CorsConfigDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param encryptionConfigDto 
     */
    putBucketEncryption(name: string, encryptionConfigDto: EncryptionConfigDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param lifecycleConfigDto 
     */
    putBucketLifecycle(name: string, lifecycleConfigDto: LifecycleConfigDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param objectLockConfigDto 
     */
    putBucketObjectLock(name: string, objectLockConfigDto: ObjectLockConfigDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param bucketPolicyDto 
     */
    putBucketPolicy(name: string, bucketPolicyDto: BucketPolicyDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param taggingDto 
     */
    putBucketTagging(name: string, taggingDto: TaggingDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param versioningConfigDto 
     */
    putBucketVersioning(name: string, versioningConfigDto: VersioningConfigDto, extraHttpRequestParams?: any): Observable<{}>;

}
