/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    health(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    ready(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    version(extraHttpRequestParams?: any): Observable<{}>;

}
