/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CorruptListDto } from '../model/models';
import { IntegrityStatusDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface IntegrityAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getIntegrityStatus(extraHttpRequestParams?: any): Observable<IntegrityStatusDto>;

    /**
     * 
     * 
     * @param limit 
     * @param offset 
     */
    listCorruptObjects(limit?: number, offset?: number, extraHttpRequestParams?: any): Observable<CorruptListDto>;

    /**
     * 
     * 
     */
    startIntegrityScrub(extraHttpRequestParams?: any): Observable<{}>;

}
