/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateKeyDto } from '../model/models';
import { CreatedKeyDto } from '../model/models';
import { EffectivePermissionsDto } from '../model/models';
import { KeySummaryDto } from '../model/models';
import { RotatedKeyDto } from '../model/models';
import { SimulateRequestDto } from '../model/models';
import { SimulateResponseDto } from '../model/models';
import { UpdateKeyDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface KeysAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createKeyDto 
     */
    createKey(createKeyDto: CreateKeyDto, extraHttpRequestParams?: any): Observable<CreatedKeyDto>;

    /**
     * 
     * 
     * @param id 
     */
    deleteKey(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    getKeyEffectivePermissions(id: string, extraHttpRequestParams?: any): Observable<EffectivePermissionsDto>;

    /**
     * 
     * 
     */
    listKeys(extraHttpRequestParams?: any): Observable<Array<KeySummaryDto>>;

    /**
     * 
     * 
     * @param id 
     */
    revokeKey(id: string, extraHttpRequestParams?: any): Observable<KeySummaryDto>;

    /**
     * 
     * 
     * @param id 
     */
    rotateKey(id: string, extraHttpRequestParams?: any): Observable<RotatedKeyDto>;

    /**
     * 
     * 
     * @param id 
     * @param simulateRequestDto 
     */
    simulateKeyAction(id: string, simulateRequestDto: SimulateRequestDto, extraHttpRequestParams?: any): Observable<SimulateResponseDto>;

    /**
     * 
     * 
     * @param id 
     * @param updateKeyDto 
     */
    updateKey(id: string, updateKeyDto: UpdateKeyDto, extraHttpRequestParams?: any): Observable<KeySummaryDto>;

}
