/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BulkDeleteDto } from '../model/models';
import { BulkDeleteResponseDto } from '../model/models';
import { LegalHoldDto } from '../model/models';
import { ListObjectsResponseDto } from '../model/models';
import { ObjectMetaDto } from '../model/models';
import { ObjectTaggingDto } from '../model/models';
import { ObjectVersionsResponseDto } from '../model/models';
import { PresignRequestDto } from '../model/models';
import { PresignedUrlDto } from '../model/models';
import { RetentionDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ObjectsAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param name 
     * @param bulkDeleteDto 
     */
    batchDeleteObjects(name: string, bulkDeleteDto: BulkDeleteDto, extraHttpRequestParams?: any): Observable<BulkDeleteResponseDto>;

    /**
     * 
     * 
     * @param name 
     * @param path Object key; may contain \&quot;/\&quot; and is percent-encoded once.
     */
    deleteObject(name: string, path: any, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     */
    deleteObjectTagging(name: string, key: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param path Object key; may contain \&quot;/\&quot; and is percent-encoded once.
     */
    getObject(name: string, path: any, extraHttpRequestParams?: any): Observable<ObjectMetaDto>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     */
    getObjectLegalHold(name: string, key: string, extraHttpRequestParams?: any): Observable<LegalHoldDto>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     */
    getObjectRetention(name: string, key: string, extraHttpRequestParams?: any): Observable<RetentionDto>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     */
    getObjectTagging(name: string, key: string, extraHttpRequestParams?: any): Observable<ObjectTaggingDto>;

    /**
     * 
     * 
     * @param name 
     * @param prefix 
     * @param keyMarker 
     * @param versionIdMarker 
     * @param maxKeys 
     */
    listObjectVersions(name: string, prefix?: string, keyMarker?: string, versionIdMarker?: string, maxKeys?: number, extraHttpRequestParams?: any): Observable<ObjectVersionsResponseDto>;

    /**
     * 
     * 
     * @param name 
     * @param prefix 
     * @param delimiter 
     * @param marker 
     * @param limit 
     */
    listObjects(name: string, prefix?: string, delimiter?: string, marker?: string, limit?: number, extraHttpRequestParams?: any): Observable<ListObjectsResponseDto>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     * @param presignRequestDto 
     */
    presignObject(name: string, key: string, presignRequestDto: PresignRequestDto, extraHttpRequestParams?: any): Observable<PresignedUrlDto>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     * @param legalHoldDto 
     */
    putObjectLegalHold(name: string, key: string, legalHoldDto: LegalHoldDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     * @param retentionDto 
     */
    putObjectRetention(name: string, key: string, retentionDto: RetentionDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param key 
     * @param objectTaggingDto 
     */
    putObjectTagging(name: string, key: string, objectTaggingDto: ObjectTaggingDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param path Object key; may contain \&quot;/\&quot; and is percent-encoded once.
     */
    uploadObject(name: string, path: any, extraHttpRequestParams?: any): Observable<{}>;

}
