/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ReconcileJobDto } from '../model/models';
import { ReconcileRequestDto } from '../model/models';
import { ReplicationStatusDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReplicationAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param jobId 
     */
    getReconcileJob(jobId: string, extraHttpRequestParams?: any): Observable<ReconcileJobDto>;

    /**
     * 
     * 
     */
    getReplicationStatus(extraHttpRequestParams?: any): Observable<ReplicationStatusDto>;

    /**
     * 
     * 
     * @param reconcileRequestDto 
     */
    startReconcile(reconcileRequestDto: ReconcileRequestDto, extraHttpRequestParams?: any): Observable<ReconcileJobDto>;

}
