/**
 * OpenBucket Admin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangePasswordDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SettingsAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param changePasswordDto 
     */
    changePassword(changePasswordDto: ChangePasswordDto, extraHttpRequestParams?: any): Observable<{}>;

}
