/**
 * `@openbucket/api-client` — the OpenAPI-generated admin API client (§5.13/§5.16).
 *
 * Generated by `nx run api-client:generate` (openapi-generator typescript-angular)
 * from the backend's exported OpenAPI document. Do NOT hand-edit `./lib` — re-run
 * the target. The SPA wires it via DI with `provideApi` (see shared/api).
 */
export * from './lib';
